# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

pw = SecureRandom.hex(5)
User.create(email: "defaultadvisor@101.net", password: pw, password_confirmation: pw, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", baserole: "staff", staffrole:"advisor")
Profile.create(user_id: User.find_by(email: "defaultadvisor@101.net").id, fname: "AdvisorTest", lname: "Advisor", skype: "testonly", nickname: "testadvisor", artist: 1, advisor: 1, bio: "I am a default account and you should never see me.")

pw = SecureRandom.hex(5)
User.create(email: "defaultartist@101.net", password: pw, password_confirmation: pw, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", baserole: "staff", staffrole:"artist")
Profile.create(user_id: User.find_by(email: "defaultartist@101.net").id, fname: "ArtistTest", lname: "Artist", skype: "testonly-2", nickname: "testartist", artist: 1, advisor: 1, bio: "I am a default account and you should never see me.")

User.create!([
  {email: "rhof@101.net", password: "abcbac101", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-08-12 06:17:50", last_sign_in_at: "2015-08-12 06:17:50", current_sign_in_ip: "10.20.80.73", last_sign_in_ip: "10.20.80.73", confirmation_token: "d1aaacef1f6e16fe9e64f3db7185682af7f8d194fdb25f9458b23cca00773ee6", confirmed_at: "2015-08-12 06:17:35", confirmation_sent_at: "2015-08-12 06:17:05", unconfirmed_email: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, baserole: 1, staffrole: 5, clientstatus: 2, refid: nil, recruiter: false},
  {email: "harv@101.net", password: "abcbac101", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 18, current_sign_in_at: "2015-08-20 08:51:24", last_sign_in_at: "2015-08-19 05:36:22", current_sign_in_ip: "10.20.80.73", last_sign_in_ip: "10.20.80.73", confirmation_token: "60037ed1e75c4987773825fbb5064979ceb82fe6dc5d5660013b33b9daf3e00d", confirmed_at: "2015-08-09 13:34:38", confirmation_sent_at: "2015-08-09 13:34:25", unconfirmed_email: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, baserole: 1, staffrole: 5, clientstatus: 2, refid: nil, recruiter: false}
])
Profile.create!([
  {user_id: User.find_by(email: "rhof@101.net").id, fname: "Rob", lname: "Hoffa", birthday: "2015-08-12", paypal: nil, skype: "", country_code: "PH", nickname: "Rob", slug: "rob", avatar: nil, bio: "", artist: User.find_by(email: "defaultartist@101.net").id, advisor: User.find_by(email: "defaultadvisor@101.net").id, recruitertos: false, selected_channel_id: nil, onboarded: nil},
  {user_id: User.find_by(email: "harv@101.net").id, fname: "Harv", lname: "Withington", birthday: "1975-11-01", paypal: nil, skype: "andycapp328", country_code: "PH", nickname: "Harv", slug: "harv", avatar: nil, bio: "", artist: User.find_by(email: "defaultartist@101.net").id, advisor: User.find_by(email: "defaultadvisor@101.net").id, recruitertos: false, selected_channel_id: nil, onboarded: nil}
])
Plan.create!([
  {name: "Unmanaged", price: 0, credits: 0, period: 0, description: "Unmanaged - no credits, reviews, or charges", includes_review: false, available: true},
  {name: "Standard", price: 3000, credits: 1000, period: 0, description: "Standard - $30 monthly, includes 1000 credits and a channel review", includes_review: true, available: true},
  {name: "Unmanaged (Annual)", price: 0, credits: 0, period: 1, description: "Unmanaged - no credits, reviews, or charges", includes_review: false, available: true}
])
ChannelCategory.create!([
  {description: "Cars & Vehicles", slug: "cars-vehicles"},
  {description: "Comedy", slug: "comedy"},
  {description: "Education", slug: "education"},
  {description: "Entertainment", slug: "entertainment"},
  {description: "Film & Animation", slug: "film-animation"},
  {description: "Gaming", slug: "gaming"},
  {description: "How-To & Style", slug: "how-to-style"},
  {description: "Music", slug: "music"},
  {description: "News & Politics", slug: "news-politics"},
  {description: "Non-profits & Activism", slug: "non-profits-activism"},
  {description: "People & Blogs", slug: "people-blogs"},
  {description: "Pets & Animals", slug: "pets-animals"},
  {description: "Science & Technology", slug: "science-technology"},
  {description: "Sports", slug: "sports"},
  {description: "Travel & Events", slug: "travel-events"}
])
Product.create!([
  {name: "Motion Graphic - Intro", preview: "", price: 350, description: "A single channel intro based on one of our motion graphic templates.", custom: "intro", status: 0, type: "MotionGraphicProduct"},
  {name: "Motion Graphic - Lower-Third", preview: "", price: 100, description: "A single lower-third graphic based on one of our motion graphic templates.", custom: "lower_third", status: 0, type: "MotionGraphicProduct"},
  {name: "Motion Graphic - Background", preview: "", price: 100, description: "A single motion background based on one of our motion graphic templates.", custom: "background", status: 0, type: "MotionGraphicProduct"},
  {name: "Motion Graphic - Title Card", preview: "", price: 150, description: "A single title_card graphic based on one of our motion graphic templates.", custom: "title_card", status: 0, type: "MotionGraphicProduct"},
  {name: "Motion Graphic - End Card", preview: "", price: 250, description: "A single end-card graphic based on one of our motion graphic templates.", custom: "end_card", status: 0, type: "MotionGraphicProduct"},
  {name: "Motion Graphic - Countdown", preview: "", price: 150, description: "A single countdown graphic based on one of our motion graphic templates.", custom: "countdown", status: 0, type: "MotionGraphicProduct"}
  
])
MotionGraphicCollection.create!([
  {name: "Frosted", description: "", slug: "frosted", preview: nil},
  {name: "Splattery", description: "", slug: "splattery", preview: nil},
  {name: "Metal Sheen", description: "", slug: "metal-sheen", preview: nil},
  {name: "Short Circuit", description: "", slug: "short-circuit", preview: nil},
  {name: "Champagne 3D", description: "", slug: "champage-3d", preview: nil},
  {name: "Long Shadow", description: "", slug: "long-shadow", preview: nil}
])
MotionGraphic.create!([
  {name: "Lower-Third - Frosted - Slide In", category: 1, vidurl: "XxQ0TFS-zsM", description: "A frosty lower third for your videos.", user_id: User.find_by(email: "harv@101.net").id, slug: "lower-third-frosted-slide-in", preview: "Lower_Third_-_Frosted_-_Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Frosted').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Lower-Third').id},
  {name: "Intro - Splattery - Camera Pan", category: 0, vidurl: "eV6gFE2skus", description: "Get a splash of colour in your intro with Splattery!", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-splattery-camera-pan", preview: "Intro-Splattery-Sample-Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Splattery').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id},
  {name: "Intro - Metal Sheen - Illuminate", category: 0, vidurl: "9MAGOFgI45g", description: "A moody metallic reveal for your intro.", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-metal-sheen-left-to-right-illuminate", preview: "Intro-Metal-Sheen-Sample-Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Metal Sheen').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id},
  {name: "Intro - Long Shadow - Type On", category: 0, vidurl: "9MAGOFgI45g", description: "Get that low afternoon sunlight effect in this simple abstract intro.", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-long-shadow-reveal-left-to-right", preview: "Intro-Long-Shadow-Sample-Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Long Shadow').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id},
  {name: "Intro - Short Circuit - Illuminate", category: 0, vidurl: "WbcxkqmCSDQ", description: "This intro is anything but static -- because it's... er... buzzing with static! Electrify your intro!", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-short-circuit-illuminate", preview: "Intro-Short-Circuit-Sample-Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Short Circuit').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id},
  {name: "Intro - Champagne 3D - Camera Pan", category: 0, vidurl: "4TrQITKBq3w", description: "Get your glitch on with Champagne 3D!", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-champagne-3d-camera-pan", preview: "Intro-Champagne-3D-Sample-Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Champagne 3D').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id},
  {name: "Intro - Frosted - Pan and Focus", category: 0, vidurl: "2WW_jxuvoE4", description: "Have your logo and text emerge from behind frosted glass.", user_id: User.find_by(email: "harv@101.net").id, slug: "intro-frosted-pan-and-focus", preview: "Intro_-_Frosted_-_Thumbnail.png", motion_graphic_collection_id: MotionGraphicCollection.find_by(name: 'Frosted').id, custom_fields: "{\r\n    \"input_fields\": [\r\n        {\r\n            \"name\": \"Main Text\",\r\n            \"type\": \"text\",\r\n            \"default\": \"[your text]\"\r\n        },\r\n        {\r\n            \"name\": \"Main Text Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#888\"\r\n        },\r\n        {\r\n            \"name\": \"Background Color\",\r\n            \"type\": \"color\",\r\n            \"default\": \"#08A\"\r\n        },\r\n        {\r\n            \"name\": \"Background Opacity\",\r\n            \"type\": \"slider\",\r\n            \"default\": \"100\",\r\n            \"parameters\": {\r\n                        \"max\": 100,\r\n                        \"min\": 0\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Logo Image\",\r\n            \"type\": \"image\",\r\n            \"default\": \"\"\r\n        }\r\n    ]\r\n}", product_id: Product.find_by(name: 'Motion Graphic - Intro').id}
])

# Can't count on user_id being what you want :) 
harv = User.find_by(email: 'harv@101.net')

News.create!([
  {user_id: harv.id, title: "The network101 portal is launched!", content: "It has been a hard slog, but the network101 portal is finally in beta. \r\n\r\nHave a sticky-beak around and let us know what's working, what you'd like to change, and which parts are complete garbage! \r\n\r\nWe're discussing it all over on  [the forum](http://forum.101.net) so make sure you join us there.", category: 0, vidurl: "", slug: "the-network101-portal-is-finally-launched", staffonly: false}
])